### ISSUE TITLE
How to run parse docker and the mongodb docker on different hosts?

### ISSUE THREAD

**Issue by rayyoungnext** [bitnami/bitnami-docker-parse#42]
I was able to follow the instructions to get the parse docker and mongodb docker running on the same host. However, I am not able to run them on different hosts. Any help is appreciated. Thanks.

**Comment by juan131** [comment]
The main problem when running the containers on different hosts is that you cannot create an internal Docker network so you need to solve a lot of problems you didn't have before.

For example, you need to expose the MongoDB database port since now you need to access from the outside to the database, so you also need to add a new security label to Mongo (allowing connections from certain IPs and adding authentication).


Why don't you give the [Parse Helm Chart](https://github.com/kubernetes/charts/tree/master/stable/parse) a try? It deploys the Parse+MongoDB solution on K8s so you can easily manage a Parse cluster.
