### ISSUE TITLE
Adding Kue Job Scheduler

### ISSUE THREAD

**Issue by johnnyzen** [bitnami/bitnami-docker-parse#46]
Hi there

First of all, many thanks for your docker images.

I would like to schedule some cloud jobs using Kue (https://medium.com/@AGordeev/how-to-get-parse-background-job-functionality-on-parse-server-6bb86f210d09)

Or is there background job functionality already (using cron?)

Please can you advise the best approach for adding this?

I am a bit of a newbie.

Best wishes

Johnny

**Comment by juan131** [comment]
Hi @johnnyzen 

> Or is there background job functionality already (using cron?)

There are no cron jobs configured on this Docker image.

> I would like to schedule some cloud jobs using Kue 

I took a look to the guide you shared and Kue needs Redis in order to work. Redis is not included in this image but you can include it by modifying the [docker-compose.yaml](https://github.com/bitnami/bitnami-docker-parse/blob/master/docker-compose.yml) (check like other solutions like [Discourse use Redis](https://github.com/bitnami/bitnami-docker-discourse/blob/master/docker-compose.yml))

Once you have Kue configured to use Redis (externally) proceed following the rest of the guide
